### ISSUE TITLE
v11 compatibility?

### ISSUE THREAD

**Issue by Krysztophe** [orgrim/pg_back#17]
In v11, if I understand correctly, some information from pg_db_role_setting that were dumped by `pg_dumpall -g` are now saved by  `pg_dump` and can restored only with `pg_restore --create`... but you need `--create` with an `pg_dump -Fp`, or you lose this info.

Will pg_back be compatible with this?

**Comment by orgrim** [comment]
Hello,

By default, pg_back runs `pg_dump -Fc`, so it is up to the user to run `pg_restore` with `--create` as of v11. People who want to configure pg_back to make plain dumps will have to put `--create` in `PGBK_OPT`, but dumping in plain format is kind of missing the point of using pg_back...

**Comment by Krysztophe** [comment]
Well, some people with a low volume may like to have a humain-readable dump. 
Maybe add the hint about PGBK_OPT in the doc and/or a comment?

**Comment by orgrim** [comment]
Well, the doc mostly being non-existant, I guess we could work on the comment for PGBK_OPTS in pg_back.conf.

If you have the time, feel free to send a PR.

Thanks

**Comment by orgrim** [comment]
Thanks for the contribution.
