### ISSUE TITLE
Issue with pg_dumpacl command detection

### ISSUE THREAD

**Issue by tohtor** [orgrim/pg_back#19]
Hi,
According to the doc, when PGBK_BIN is empty, it means search the PATH. In this particular case, the command pg_dumpacl is not detected:
https://github.com/orgrim/pg_back/blob/21a117aa454da8e9f48f5fcb001f06969ef2b109/pg_back#L259

You can test this yourself by using it with an other command:
``
PGBK_BIN=""; [ -x "${PGBK_BIN}ls" ] && echo "cmd found" || echo "cmd not found"
``

The test should use "command -v" to detect pg_dumpacl. I have forked the project and commit a correction here: https://github.com/tohtor/pg_back/commit/81e583e459881429e0d10d5feaeb5020c6221b12

Regards

**Comment by orgrim** [comment]
Hello,

Thanks for the report. Do you mind submitting a pull request with your fix?

Regards
