### ISSUE TITLE
Issue with purging backups

### ISSUE THREAD

**Issue by tohtor** [orgrim/pg_back#20]
Hi,
The purge is not correct with PGBK_MIN_KEEP variable because it process two type of files (.dump and .sql) at the same time. It results in a wrond deletion of backups. 

Let's say PGBK_MIN_KEEP=4 and you have 5 backups of "foo" db (so 10 files total because one sql and one dump file per backup)
- the good behaviour will be to delete the last backup (i.e: 2 files total) to keep the 4 most recent backups.
- the current behaviour deletes the last 6 older files (i.e: the 3 older backups) and the result after purge is 4 files (or 2 backups) left (i.e: the value of PGBK_MIN_KEEP).

(And I didn't mention the case where PGBK_MIN_KEEP is odd and backups are partially deleted because of that).

The solution is simple, just test for each type of file individually. I have forked the project and commit a solution here:  https://github.com/tohtor/pg_back/commit/7560822462b6bd584700bb5b05425c5ba2077cc5

Regards,

PS: sorry if it's not clear enough, my mother tongue is french, it's hard to explain something like this in english.

**Comment by orgrim** [comment]
Hello,

Thanks for the report. I'll fix this when I have more time.

Regards,

**Comment by tohtor** [comment]
Hi,
I can also provide a PR if you want.
Check https://github.com/tohtor/pg_back/commit/7560822462b6bd584700bb5b05425c5ba2077cc5
