### ISSUE TITLE
single quotes in $PGBK_OPTS are not handled as expected

### ISSUE THREAD

**Issue by neiaberau** [orgrim/pg_back#24]
if the for example -T 'tmp*' is used in PGBK_OPTS, the table is not excluded, this only seems to work if eval is used. 
instead of:
`if ! ${PGBK_BIN}pg_dump $OPTS $PGBK_OPTS -f "${dump}" $db; then`
this could work (not yet tested for all cases, also need to handle spaces in $dump)
`if ! eval "${PGBK_BIN}pg_dump $OPTS $PGBK_OPTS -f ${dump} $db"; then`

**Comment by orgrim** [comment]
Hello,

If you remove the singles quotes, the tables are excluded: PGBK_OPTS="-Fc -T tmp*"

To handle spaces correctly, PGBK_OPTS must become an array with each single argument quoted as its elements. Then pg_dump must be called with "${PGBK_OPTS[@]}". This is the only clean and secure way to handle spaces. Of course, it would break backward compatibility...

Regards,

**Comment by neiaberau** [comment]
I had the single quotes in my original setup, as the documentation of postgres said so. 

That should work most of the time I guess, however would that not, if by chance a file named tmp…  exists, expanded to the filename?

But of course, you are absolutely right, the array solution is the only way to treat arguments safely.

**Comment by orgrim** [comment]
Indeed it is expanded. So I guess the array is the only way to go...
