### ISSUE TITLE
1.8 breaks compatibility for PGBK_OPTS

### ISSUE THREAD

**Issue by Krysztophe** [orgrim/pg_back#27]
I know this is a consequence of #24 . I open the issue because it may be useful to others with the same problem. 

This does not work anymore :

`PGBK_OPTS='-Fd -Z8 --jobs=2'`

This seems to work: 

`PGBK_OPTS=("-Fd" "-Z8" "--jobs=2")`

An error message to ease the upgrade would be nice (if no`(` is found in PGBK_OPTS, for example).

**Comment by orgrim** [comment]
Hello,

it is documented in pg_back.conf. Unfortunately, there is no easy way to check if a variable is a array or not with bash...

Regards,

**Comment by Krysztophe** [comment]
pg_back.conf will typically NOT be rewritten through an upgrade. People may upgrade the script and it will fail without much information.

Perhaps change the parameter name, and throw a FATAL if the old parameter is still around?
