### ISSUE TITLE
Save config files

### ISSUE THREAD

**Issue by Krysztophe** [orgrim/pg_back#30]
pg_back should include configuration files.

It could as simple than `CONFIG_DIRECTORIES_TO_BACKUP="/etc/postgresql/  /var/lib/postgres/scripts"` and a tar. 

A copy from `pg_settings` is another option (@tilkow  a done some things about it) but (in my mind) overkill, or the output from `show all`.

**Comment by orgrim** [comment]
The tar of those directories this would only work when the script is run from localhost.

A query from pg_settings or show all would only show current settings and would miss the real value if something has been set in pg_db_role_setting

**Comment by Krysztophe** [comment]
80%  pg_back instances are used on the db instance. The result of pg_settings is much better than nothing...

**Comment by orgrim** [comment]
OK
