### ISSUE TITLE
Add timeout behaviour when dumping standby in case of AccessExclusiveLocks

### ISSUE THREAD

**Issue by fljdin** [orgrim/pg_back#32]
In some case of AccessExclusiveLocks on primary node, a internal loop waits for pausing replication when dumping on a standby node, with the following message:
```
The slave database has exclusive locks (vacuum full, truncate or other locking command) running on master
Resuming replication for 10s
```
(feature introduced in commit 3159de56792cbd77ba57a42b342b78e14ef53655)

If active session is still running during a large amount of time, it could be necessary to abort `pg_back` to avoid multiple executions on a daily routine, by adding a new parameter called `PGBK_PAUSE_TIMEOUT` to manage a properly exit of internal loop.

**Comment by orgrim** [comment]
Hello,

Fixed. Thank you for the contribution @fljdin!
