### ISSUE TITLE
incompatibility with pgsql earlier than 9.x

### ISSUE THREAD

**Issue by bonidier** [orgrim/pg_back#4]
Hi Orgrim,

The postgresql function you're using to check recovery status only works since PostGreSQL 9.x

```
# psql -V
psql (PostgreSQL) 8.4.20

# ./pg_back -c ./pg_back.conf
2016-02-05 10:28:58 CET  INFO: preparing to dump
2016-02-05 10:28:58 CET  INFO: target directory is /var/backups/postgresql
ERROR:  function pg_is_in_recovery() does not exist
```

May be there is an alternative to your commands for PgSQL earlier than 9
For now, I've simply replaced "die" with and echo on line 162
https://github.com/orgrim/pg_back/blob/master/pg_back#L162

**Comment by orgrim** [comment]
I guess that is a good fix. I guess I'll use info, so that it can be silenced with the quiet mode and won't annoy people every run.

**Comment by orgrim** [comment]
fixed. thank you for your contribution.
