### ISSUE TITLE
v2 installation from source fails

### ISSUE THREAD

**Issue by Krysztophe** [orgrim/pg_back#43]
Note: I don't know anything about go, just following the README
```
postgres@monolithe:~$ go get -u github.com/orgrim/pg_back
package embed: unrecognized import path "embed" (import path does not begin with hostname)
```
(Same problem on 2 Ubuntu 20.04 and 1 Debian 10.8 with `gccgo-go`)

**Comment by orgrim** [comment]
You need Go 1.16 to build pg_back from source. You can download a binary distribution of Go directly from golang.org

Otherwise, you can just use the binary file attached to the release.

**Comment by Krysztophe** [comment]
OK. I'm making a small PR doc for this and other small things.

**Comment by orgrim** [comment]
Merged. Thanks
