### ISSUE TITLE
Passfile & connection on Windows

### ISSUE THREAD

**Issue by Krysztophe** [orgrim/pg_back#47]
This is perfectly working configuration file for pg_back2 on Windows (2016):
(I had to use the long connection string to allow no-SSL connections, as SSL is not activated by default)

```ini
bin_directory = "C:\Program Files\PostgreSQL\13\bin"
dbname = " sslmode=disable host=localhost port=13666 user=postgres dbname=postgres password=yiu5"
backup_directory = "P:\dumps"
timestamp_format = legacy
purge_older_than = 1
purge_min_keep = 1
format = directory
pg_dump_options = -Z8 -j2
exclude_dbs = postgres, postgis_31_sample, postgres2
with_templates=true

[pgbench]
format = custom
pg_dump_options = '-Z9 -j1'

[template1]
format = plain

[template0]
format = custom
pg_dump_options = '-Z9 -j1'
```

Obviously I don't want the password in clear, so I tested but this does not work.
```
dbname = "sslmode=disable host=127.0.0.1 port=13666 user=postgres dbname=postgres passfile='p:/pg_back2/pgpass' "
```

All of these are perfectly fine connection strings that work, but fail with pg_back:
```
%P%\pg_dumpall  -g -d "sslmode=disable host=127.0.0.1 port=13666 user=postgres dbname=postgres passfile='p:/pg_back2/pgpass' "
%P%\pg_dumpall  -g -d "sslmode=disable host=127.0.0.1 port=13666 user=postgres dbname=postgresmd5 passfile='p:/pg_back2/pgpass' "
%P%\pg_dumpall  -g -d "postgresql://postgres@127.0.0.1:13666/postgres?sslmode=disable&passfile=p:/pg_back2/pgpass"
```
Errors are different, but it seems that the password are corrupted somewhere in the process:

```
P:\pg_back2>P:\pg_back2\pg_back.exe -v -c pg_back2.conf -d "postgresql://postgres@127.0.0.1:13666/postgres?sslmode=disable&password=yiu5" 
2021/04/03 19:02:59.893371 INFO: dumping globals
2021/04/03 19:02:59.893371 FATAL: pg_dumpall -g failed: illegal character in keyword
```

Instead of `p:/pg_back2/pgpass`, a pass.conf in %APPDATA%/postgresql does not work better.

I've tried quotes, no quotes, slash, antislash, nothing works.

It is not better when the target is an instance on Linux. 

I've found no problem on pg_back2 for Linux.

I hope I've just made a stupid mistake.

Full debug log sent in private.

**Comment by orgrim** [comment]
Hello,

Thanks for the report.

You can use `parallel_backup_jobs` et `compress_level` instead of putting `-j `and `-Z` in `pg_dump_options `.

The parsing of `postgresql://` URIs is not currently not supported in pg_back, only `keyword=value` connection strings are.

The passfile keyword is not used by the `lib/pq` Go module: https://github.com/lib/pq/blob/master/conn.go#L191-L210, you need to pass the file name with the PGPASSFILE environment variable.

It would be interesting to run the unit tests on Windows as well, just in case :-).

Regards,
