### ISSUE TITLE
Quiet/Cron Mode

### ISSUE THREAD

**Issue by Querschlag** [orgrim/pg_back#53]
Good to see version 2 having package/binary releases and overall getting better.
There is just one feature from 1.x that's missing for me and that is the `-q` flag to run `pg_back` in "quiet" mode. 
I normally run `pg_back` as a cron job and have mailing set up, so any output on STDOUT or STDERR will be sent to my inbox. However I only want to be notified about critical errors and want to suppress info messages like `INFO: dumping instance configuration`.

I tried `sudo -u postgres pg_back > /dev/null` but still seeing terminal output, as the program only outputs to STDERR.
Once I redirected STDERR to STDOUT `sudo -u postgres pg_back > /dev/null 2>&1` I got the desired output. This however also discards any potential error and wont trigger an email (no output) if `pg_back` encounters a problem.

To fix this I propose the following changes:
1. Only output errors/warnings to STDERR and information, debug or verbose output to STDOUT
2. A new CLI flag to omit any non critical output e.g. only errors/warnings to STDERR

**Comment by orgrim** [comment]
Hi, that's correct, I totally forgot about this option, which is precisely made for cron.

I'll go for option 2 only, and make the quiet mode only print message from the WARN level and above. Error message shall go to stderr.

Regards

**Comment by orgrim** [comment]
@Querschlag please checkout PR #54. Thanks.

**Comment by orgrim** [comment]
@Querschlag does PR #54 works for you? Thanks.

**Comment by Querschlag** [comment]
Sry for taking so long to respond. I managed to build the project with Go 1.16.4 and can confirm that the CLI flag works as intended.

**Comment by orgrim** [comment]
Great. Thanks.
