### ISSUE TITLE
Older pg version support

### ISSUE THREAD

**Issue by fljdin** [orgrim/pg_back#59]
Hello,
Latest version of pg_back (2.0.1) seems not compatible with postgresql 9.2 and lower.
Especially due to nonexistent "-d connstr" option with `pg_dumpall`.

```
2021/10/29 02:00:02 INFO: dumping globals
2021/10/29 02:00:02 ERROR: /usr/pgsql-9.1/bin/pg_dumpall: invalid option -- 'd'
2021/10/29 02:00:02 ERROR: Try "pg_dumpall --help" for more information.
2021/10/29 02:00:02 FATAL: pg_dumpall -g failed: exit status 1
```
Could you please add a disclaimer for older versions? Or take away this option?
Regards

**Comment by orgrim** [comment]
@fljdin could you please confirm #60 fixes the issue?

Thanks

**Comment by fljdin** [comment]
HI,

Could you please tell me how install or build your source with golang?
As described in README, `go get` command seems deprecated

```
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

Regards
