### ISSUE TITLE
Encryption: problems finding the encryption key & other returns

### ISSUE THREAD

**Issue by Krysztophe** [orgrim/pg_back#64]
I've just compiled from master to test the encryption (Linux ubuntu 20.04, golang-1.16 installed)

- With nothing about encryption in the `pg_back2.conf`, this works (I get `.age` files):
```bash
/opt/pg_back2/pg_back2.bin.master --encrypt --cipher-pass AZERTYUIOP -vc /etc/postgresql/14/defo/pg_back2.conf
```

-  This fails with the env variable (exported or not):

```bash
$ export PGBK_PASSPHRASE=AZERTYIUOP
$ echo $PGBK_PASSPHRASE
AZERTYUIOP

$ /opt/pg_back2/pg_back2.bin.master --encrypt  -vc /etc/postgresql/14/defo/pg_back2.conf
...
2021/12/20 19:34:48.665811 FATAL: some error encountered in postprocessing: encryption failed: could not encrypt /PGDATA2/DUMPS/defo14/pg_globals_2021-12-20_19-34-48.sql: failed to create recipient from password: passphrase can't be empty
```

- It works with this in the conf file:
```ini
encrypt = true
cipher_passphrase = AZERTYUIOP
```

- The encryption does not seem to work if defined only on DB level this way:
```ini
[pgbench5p10]
encrypt = true
cipher_passphrase = AZERTYUIOP
```
That's understandable but, IMHO, should be documented and raise an error 

- I find there is an incoherence between `--cipher-pass` and `cipher-passhphrase = ...`: it's easy to confuse both, especially as the `README.md` speaks only the 1st one.
(And there is no error, but this is for another issue)

**Comment by Krysztophe** [comment]
About this `$PGBK_PASSPHRASE`: 

-with some `fmt.Printf`, I've found that it is read and its length computed, it fails later
-it is read only with a `--encrypt`, never with `encrypt = true`.

**Comment by orgrim** [comment]
Hello,

PR #66 should fix that. Please take into account that I have rename the options so that they can be guessed easily:

* --cipher-pass stays
* cipher_passphrase -> cipher_pass
* PGBK_PASSPHRASE -> PGBK_CIPHER_PASS

For now there is no encryption at database level, mostly to keep the decryption straightforward.

Regards
