### ISSUE TITLE
Backup retention policy based on the number of backups

### ISSUE THREAD

**Issue by julmon** [orgrim/pg_back#7]
Helllo,

The current way to remove older backups is based on file age, it could be awesome to apply also a retention policy based on the number of backup.

Thank you.

**Comment by orgrim** [comment]
Hello,

To ensure a reliable behavior when basing the purge on age, the naming of the dump must be in a time sortable format.

It is the case by default but this is configurable. If the user changes the format (see PGBK_TIMESTAMP), it could break the feature and remove he wrong backups.

**Comment by orgrim** [comment]
Hello

I've just found another way to implement a purge of old backups, without relying on PGBK_TIMESTAMP to get the age of backups. stat is used instead.

Commit 29c3ecf924ec5f60f4f8ec9d5d27c7912cb9816a add a new PGBK_PURGE_MIN_KEEP option allowing the keep a minimum of backups while removing old backups based on their age. By configuring PGBK_PURGE to 0 and using PGBK_PURGE_MIN_KEEP, you get a policy based on the number of backups.
