### ISSUE TITLE
misc Feedback

### ISSUE THREAD

**Issue by yene** [orgrim/pg_back#77]
hi, 

it is a cool tool 👍
Just a note, it took me some time to configure the password. Can the password be provided by environment variable?
Also I think the tool requires superuser permissions which you don't get on AWS RDS or Azure postgres.

**Comment by orgrim** [comment]
Hi,

Thanks for the feedback.

When connecting to Postgres, all usual PG* environment variables from the libpq are recognized. You can give the password with the PGPASSWORD env var.

Yes the tool requires superuser privileges to execute pg_dumpall -g, which is always the first step in a run. I'll see if I can test it with big dbaas (aws, azure, gcp)

Regards
