### ISSUE TITLE
Providing --bin-directory fails with a "not a directory" error

### ISSUE THREAD

**Issue by pgiraud** [orgrim/pg_back#81]
``` shell
$ which pg_dump
/usr/bin/pg_dump
$ /tmp/pg_back  -B /usr/bin/pg_dump -b /tmp
2022/06/17 11:46:34 WARN: failed to retrieve version of pg_dump: fork/exec /usr/bin/pg_dump/pg_dump: not a directory
2022/06/17 11:46:34 FATAL: provided pg_dump is older than 8.4, unable use it.
```

Could this be related to https://github.com/orgrim/pg_back/issues/78 ?

This error doesn't seem to happen with version 2.1.0 (installed via .deb package).

**Comment by orgrim** [comment]
Hi,

In your example, `/usr/bin/pg_dump` is not a directory, -B expects a directory containing the postgres client tools, so you should give it `/usr/bin` instead. I agree the message and failure could be better, but there isn't any issue with -B imo.

#78/#79 fixes the issue where -B was completely ignored on OS other than windows, not getting this error with your set of options with 2.1.0 is a side effect of #78

I agree the message and failure could be better, but there isn't any issue with -B imo. I'll see if I can make it fail better

Regards

**Comment by pgiraud** [comment]
My bad. Thanks for the clarification.
