### ISSUE TITLE
"pg_back" is an invalid Debian package name ("_" not allowed)

### ISSUE THREAD

**Issue by jmbourdaret** [orgrim/pg_back#84]
"**_pg_back_**" is an invalid package name. 

It does not comply with the **Debian** package naming rules :
https://www.debian.org/doc/debian-policy/ch-controlfields.html#source

> Package names (both source and binary, see [Package](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-package)) must consist only of lower case letters (a-z), digits (0-9), plus (+) and minus (-) signs, and periods (.).

Looks like debian does not allow `_` (underscore) in package names.

Not much of an issue most of the time, but I stumbled upon this `debsums` tool which was reporting a warning about this:

```bash
$ sudo debsums -ce
debsums: invalid package name 'pg_back'
```

There might be others out there who might be real picky...

**Comment by orgrim** [comment]
Hi, thanks for the info.
