### ISSUE TITLE
Couldnt connect to db

### ISSUE THREAD

**Issue by sajiljosephs** [orgrim/pg_back#90]
#pg_back -c pg_back.conf
INFO: dumping globals
ERROR: pg_dumpall: error: could not connect to database "postgres"
INFO: waiting for postprocessing to complete
FATAL: pg_dumpall -g failed: exit status 1

While trying manually to connect with pg_dumpall connects successfully

pg_dumpall -h localhost -p 5432 -U postgres -d postgres -W

Conf: 
host = localhost
port = 5432
user = "postgres"
dbname = "postgres"

Password for the user postgres is stored in ~/.pgpass
Do we have a detailed log to see whats the exact error ?

**Comment by orgrim** [comment]
Hi. Could you please run pg_back with -v to show the pg_dumpall command run?

**Comment by sajiljosephs** [comment]
DEBUG: pg_dumpall version is: 150002
DEBUG: running: /usr/bin/pg_dumpall -g -w -l postgres -d application_name=pg_back dbname=postgres host=localhost port=5432 user=postgres -f /var/backups/postgresql/pg_globals_2023-03-24T14:36:26+05:30.sql
ERROR: pg_dumpall: error: could not connect to database "postgres"

**Comment by orgrim** [comment]
If you run: /usr/bin/pg_dumpall -g -w -l postgres -d "application_name=pg_back dbname=postgres host=localhost port=5432 user=postgres", do you get the issue? Also try it without -w, please.

**Comment by sajiljosephs** [comment]
Without -w it asks for password and it connects. 
With -w error: 
pg_dumpall: error: could not connect to database "postgres"

**Comment by sajiljosephs** [comment]
$ ll /home/sajil/.pgpass
-rw------- 1 sajil sajil 17 Mar 28 16:16 /home/sajil/.pgpass

**Comment by sajiljosephs** [comment]
When I delete this .pgpass file, the error is  
ERROR: WARNING: password file "/home/sajil/.pgpass" has group or world access; permissions should be u=rw (0600) or less
which means its looking for the exact location. What could be the other possibility ?

**Comment by sajiljosephs** [comment]
Permission is this  -rw-------
And it just have the password in plain text

**Comment by sabineCa** [comment]
Hello, 
i have the same problem. i changed the permission to 777 for .pgpass and it doesn't work yet

**Comment by orgrim** [comment]
When you say "just have the password", you mean in the format `host:port:dbname:user;password`?

**Comment by sajiljosephs** [comment]
Thanks the issue is fixed with this format host:port:dbname:user:password
